#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi


# aliases
alias l='ls -lh'
alias ll='ls -lah'

alias te="open -a TextEdit"
alias vs="open -a \"Visual Studio Code\""

alias youaudio="youtube-dl -x --audio-format mp3"
alias dcom="docker-compose"
alias cat='bat'


if [[ "$OSTYPE" == "darwin"* ]]; then
  showfiles () {
    defaults write com.apple.finder AppleShowAllFiles YES
    killall Finder
  }
  hidefiles () {
    defaults write com.apple.finder AppleShowAllFiles NO
    killall Finder
  }
fi

high () { 
  reg=$(printf "|%s" "${@[@]}")
  reg=${reg:1}
  text=$(</dev/stdin)
  echo $text| grep --color -E "${reg}|$"; 
}

# pyenv
export PYENV_ROOT=$HOME/.pyenv
export PATH=$PATH:$PYENV_ROOT/shims
export PYENV_VIRTUALENV_DISABLE_PROMPT=1
if command -v pyenv 1>/dev/null 2>&1; then
    eval "$(pyenv init - --no-rehash)"
    eval "$(pyenv virtualenv-init -)"
fi

# rust
export PATH=$PATH:$HOME/.cargo/bin

# pipenv
export PIPENV_VENV_IN_PROJECT=1

# poetry
export PATH="$HOME/.poetry/bin:$PATH"

# GOOGLE CLOUD
if [ -f "$PYENV_ROOT/versions/2.7.14/bin/python" ]; then 
  export CLOUDSDK_PYTHON="$PYENV_ROOT/versions/2.7.14/bin/python"
fi

if hash direnv 2>/dev/null; then
    eval "$(direnv hook zsh)"
fi

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/Users/Vania/google-cloud-sdk/path.zsh.inc' ]; then . '/Users/Vania/google-cloud-sdk/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/Users/Vania/google-cloud-sdk/completion.zsh.inc' ]; then . '/Users/Vania/google-cloud-sdk/completion.zsh.inc'; fi
