#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi


# aliases
alias l='ls -lh'
alias ll='ls -lah'

alias te="open -a TextEdit"
alias vs="open -a \"Visual Studio Code\""

alias ff="open -a FirefoxDeveloperEdition -g"

function youaudio() {
    if [ "$#" -eq 0 ]; then
        echo "reading link from clipboard..."
        pbpaste | xargs youtube-dl -x --audio-format mp3
    else
        youtube-dl -x --audio-format mp3 $@
    fi
}


if [[ "$OSTYPE" == "darwin"* ]]; then
  showfiles () {
    defaults write com.apple.finder AppleShowAllFiles YES
    killall Finder
  }
  hidefiles () {
    defaults write com.apple.finder AppleShowAllFiles NO
    killall Finder
  }
fi

high () { 
  reg=$(printf "|%s" "${@[@]}")
  reg=${reg:1}
  text=$(</dev/stdin)
  echo $text| grep --color -E "${reg}|$"; 
}

# rust
export PATH=$PATH:$HOME/.cargo/bin


# python
export PATH="$HOME/.poetry/bin:$PATH"
export PATH="$HOME/.local/bin:$PATH"

# direnv
if hash direnv 2>/dev/null; then
    eval "$(direnv hook zsh)"
fi

# The next line updates PATH for the Google Cloud SDK.
if [ -f "$HOME/google-cloud-sdk/path.zsh.inc" ]; then . "$HOME/google-cloud-sdk/path.zsh.inc"; fi

# The next line enables shell command completion for gcloud.
if [ -f "$HOME/google-cloud-sdk/completion.zsh.inc" ]; then . "$HOME/google-cloud-sdk/completion.zsh.inc"; fi

# custom scripts
if [ -d "$HOME/bin" ]; then
  export PATH=$PATH:$HOME/bin
fi

# added by travis gem
[ -f $HOME/.travis/travis.sh ] && source $HOME/.travis/travis.sh

# brew
export PATH="/usr/local/opt/make/libexec/gnubin:$PATH"
