#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi


# aliases
alias l='ls -lh'
alias ll='ls -lah'

alias te="open -a TextEdit"
alias vs="open -a \"Visual Studio Code\""

alias youaudio="youtube-dl -x --audio-format mp3"
alias dcom="docker-compose"
alias cat='bat'


# pyenv
export PYENV_ROOT=$HOME/.pyenv
export PATH=$PATH:$PYENV_ROOT/shims
export PYENV_VIRTUALENV_DISABLE_PROMPT=1
if command -v pyenv 1>/dev/null 2>&1; then
    eval "$(pyenv init - --no-rehash)"
    eval "$(pyenv virtualenv-init -)"
fi

# rust
export PATH=$PATH:$HOME/.cargo/bin

# pipenv
export PIPENV_VENV_IN_PROJECT=1

# GOOGLE CLOUD
export CLOUDSDK_PYTHON="$PYENV_ROOT/versions/test2/bin/python"
# The next line updates PATH for the Google Cloud SDK.
if [ -f '/Users/Vania/Downloads/google-cloud-sdk/path.zsh.inc' ]; then source '/Users/Vania/Downloads/google-cloud-sdk/path.zsh.inc'; fi
# The next line enables shell command completion for gcloud.
if [ -f '/Users/Vania/Downloads/google-cloud-sdk/completion.zsh.inc' ]; then source '/Users/Vania/Downloads/google-cloud-sdk/completion.zsh.inc'; fi
